FROM node:22.18-alpine AS build

WORKDIR /app

ENV NODE_ENV development

COPY package*.json ./
RUN npm ci

WORKDIR /app
COPY . .
RUN chown -R node:node /app

USER node

EXPOSE 3001

CMD ["npm", "run", "dev"]
