services:
  books-search-engine:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./src:/app/src
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    env_file: .env
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      API_SERVER_PORT: ${API_SERVER_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_POOL_MIN: ${DATABASE_POOL_MIN}
      DATABASE_POOL_MAX: ${DATABASE_POOL_MAX}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis

  pgadmin:
    container_name: pgadmin
    env_file: .env
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: true
      PGADMIN_HOST_PORT: ${PG_ADMIN_HOST_PORT}
    ports:
      - "${PGADMIN_HOST_PORT}:80"
    networks:
      - books-engine
    depends_on:
      - booksdb

  booksdb:
    container_name: booksdb
    platform: linux/arm64
    restart: unless-stopped
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - books-engine

  redis:
    image: redis:7-alpine
    environment:
      REDIS_PORT: ${REDIS_PORT}
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redisinsight:
    image: redis/redisinsight:latest
    environment:
      REDIS_INSIGHT_PORT: ${REDIS_INSIGHT_PORT}
    container_name: redisinsight
    ports:
      - "${REDIS_INSIGHT_PORT}:5540"
    depends_on:
      - redis

volumes:
  books-engine-data:
  redis_data:

networks:
  books-engine:
    name: books-engine
    driver: bridge
